const categories =[
"Aerospace",
"Accounting",
"Administration",
"Agriculture",
"Architecture",
"Automotive",
"Banking",
"Construction",
"Counseling/Psychology",
"Culinary/Food Services",
"Customer Service",
"Education",
"Energy",
"Engineering",
"Environmental Services",
"Event Planning",
"Fashion/Beauty",
"Finance",
"Fine Arts",
"Government/Public Service",
"Graphic Design",
"Healthcare/Medicine",
"Hospitality",
"Human Resources",
"Information Technology",
"Insurance",
"Interior Design",
"Law/Legal Services",
"Manufacturing",
"Marketing",
"Media/Entertainment",
"Music/Performing Arts",
"Nonprofit/Volunteer",
"Pharmaceuticals",
"Photography/Videography",
"Public Relations",
"Real Estate",
"Research/Development",
"Retail",
"Sales",
"Social Work",
"Sports/Recreation",
"Telecommunications",
"Transportation/Logistics",
"Writing/Editing"
]

export default categories